//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiteMekkaScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexedSpot
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Category { get; set; }
        public string SpotType { get; set; }
        public string SpotLevel { get; set; }
        public string ToiletAvailable { get; set; }
        public string Directions { get; set; }
        public string Description { get; set; }
        public Nullable<bool> WindN { get; set; }
        public Nullable<bool> WindNE { get; set; }
        public Nullable<bool> WindE { get; set; }
        public Nullable<bool> WindSE { get; set; }
        public Nullable<bool> WindS { get; set; }
        public Nullable<bool> WindSW { get; set; }
        public Nullable<bool> WindW { get; set; }
        public Nullable<bool> WindNW { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    }
}
